config/routes.rb
Rails.application.routes.draw do
  
  root :to => 'events#home'
  resources :user_sessions
  resources :users
  resources :events
  resources :venues
  resources :bookmarks

  resources :events do
    resources :venues
    resources :bookmarks, only: [:create]
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  belongs_to :venue
  has_many :bookmarks
  has_many :watchers, through: :bookmarks, source: :user
end

app/models/seatgeek/event.rb
module Seatgeek

  class Event < Base
    attr_accessor :title, :category, :image_url, :tickets_url, :datetime_local, :venue_name, :api_venue_id, :city_name, :state_prov, :country_name, :avg_price, :api_event_id, :performers_id, :performers_name, :performers

    def initialize(attributes)
      @api_event_id = attributes["id"]
      @category = attributes["type"]
      @image_url = attributes['performers'][0]['image']
      @tickets_url = attributes['performers'][0]['url']
      @title = attributes["title"]
      @datetime_local = attributes["datetime_local"]
      @venue_name = attributes["venue"]["name"]
      @api_venue_id = attributes["venue"]["id"]
      @city_name = attributes["venue"]["city"]
      @state_prov = attributes["venue"]["state"]
      @country_name = attributes["venue"]["country"]
      @avg_price = attributes["stats"]["average_price"]
      @performers = attributes['performers']  #array
    end

    def self.event_search(keywords)
      response = get("/events?q=#{keywords.to_s.gsub(' ','-')}&per_page=1000&page=1&client_id=#{ENV['seatgeek_id']}&client_secret=#{ENV['seatgeek_secret']}")

      if response.empty?
        render 'index'
      else
        response["events"].map do |event|
          new(event)
        end
      end
    end

    # def self.event_search_geolocation(keywords,latitude,longitude)
    #   response = get("/events?q=#{keywords.to_s.gsub(' ','-')}&per_page=1000&page=1&lat=#{latitude}&lon=#{longitude}&datetime_utc.gte=#{year}-#{month_start}-01&datetime_utc.lt=#{year}-#{month_end}-#{Seatgeek::Event.end_of_month(month_end)}&client_id=#{ENV['seatgeek_id']}&client_secret=#{ENV['seatgeek_secret']}")
    #
    #   if response.empty?
    #     render 'index'
    #   else
    #     response["events"].map do |event|
    #       new(event)
    #     end
    #   end
    # end


    def self.end_of_month(month)
      days_in_month = [nil, "31", "28", "31", "30", "31", "30", "31", "31", "30", "31", "30", "31"]
      days_in_month[month.to_i]
    end

    def self.event_find(id)
      #Sends http request and returns json hash as response.
      response = get("/events?id=#{id}&client_id=#{ENV['seatgeek_id']}&client_secret=#{ENV['seatgeek_secret']}")
      #Creates new event object from returned events/json hash
      new(response["events"][0])
    end

    def self.event_performers_ids(event_performers_attribute)
      event_performers_attribute.map do |performer|
        performer["id"]
      end
    end

    def self.event_performers_names(event_performers_attribute)
      event_performers_attribute.map do |performer|
        performer["name"]
      end
    end

    def self.to_h(event)
      {
      api_event_id: event.api_event_id,
      category: event.category,
      image_url: event.image_url,
      tickets_url: event.tickets_url,
      title: event.title,
      datetime_local: event.datetime_local,
      venue_name: event.venue_name,
      api_venue_id: event.api_venue_id,
      city_name: event.city_name,
      state_prov: event.state_prov,
      country_name: event.country_name,
      avg_price: event.avg_price
      }
    end

  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :require_login

  def home
    render :layout => 'home_layout'
  end

  def index

    if params[:search].blank?
      # flash[:alert] = "Your search is invalid. Please enter keywords, and search again."
      render 'index'
    else
      @events = Kaminari.paginate_array(Seatgeek::Event.event_search(params[:search])).page(params[:page]).per(18)
    end
  end

  def show
    if Event.exists?(api_event_id: params[:id])
      @event = Event.find_by(api_event_id: params[:id])
    else
      new_event = Seatgeek::Event.event_find(params[:id])
      @event = Event.create( Seatgeek::Event.to_h(new_event) )
    end

    # @performers = Seatgeek::Event.event_performers_names(new_event.performers)

    @bookmark = Bookmark.new
  end

  def new

  end

  def bookmark
    @bookmark = Seatgeek::Event.event_find(params[:id])
  end

  private
    def search_params
      params.require(:event).permit(:search, :page, :id, :start_month[:month], :end_month[:month], :year[:year] )
    end

    def event_params
      params.require(:event).permit(:api_event_id, :user_id, :title, :category, :image_url, :api_venue_id, :venue, :venue_name, :tickets_url, :datetime_local, :city_name, :state_prov, :country_name, :avg_price)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<% if @events != nil %> <!--wrap form in if/else statement -->
  <div class="pagination">
    <%= paginate @events %>
    <%= page_entries_info @events, :entry_name => 'items' %></br>
  </div>

  <div id="event_index_container">
    <% @events.each do |event| %>
      <div id="card_container">
        <ul>
          <li class="event">
            <div class="cards">
              <div class="card">
                <%= link_to event_path(event.api_event_id) do %>
                  <div class="card-image">
                    <%= image_tag event.image_url %>
                  </div>
                  <div class="card-header">
                    <%= event.title %>
                  </div>
                  <div class="card-copy">
                    <% event.api_event_id %>
                    <%= event.venue_name %></br>
                    <%= Time.parse(event.datetime_local).strftime("%I:%M %p") %></br>
                    <%= Time.parse(event.datetime_local).strftime("%A %B %d") %></br>
                    <%= event.city_name.to_s + ", " + event.state_prov.to_s %></br>
                    <%= event.country_name %></br>

                  </div>
                <% end %>
              </div>
            </div>
          </li>
        </ul>
      </div>
    <% end %>
  </div>

  <div class="pagination">
    <%= paginate @events %>
  </div>

<% end %>

  </br>
  </br>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/home.html.erb
<!-- <div class="intro_page">
  <div class="concert_pic">
    <%=image_tag("concert.jpg")%>
  </div>
</div> -->

<% content_for :head do %>
  <style>
    body {
      background-color: black;
    }
  </style>
<% end %>

app/views/events/index.html.erb
<div class="main_search">
  <span class="form">
    <h4 id="tag_line">"Thousands of events and millions of tickets all in one spot!"</h3>
    <%= form_tag events_path, method: :get, authentication: false, id: 'search-form' do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search by Event, Artist, Team, or Venue"  %>
      <%= submit_tag "Search", id: "submit"%>
      <%= hidden_field_tag "latitude" %>
      <%= hidden_field_tag "longitude" %>
    <% end %>
  </span>
</div>

</br>

<div id="response_showcase">
  <%= render "form" %>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div id="event_show_container">

  <div id="event_show_image">
    <%= image_tag @event.image_url %></br></br>
    <%= button_to "Get Tickets!", @event.tickets_url, method: :get %></br></br>

    <% if current_user && !@event.watchers.include?(current_user) %>
      <%= form_for [@event, @bookmark] do |f| %>
        <%= f.submit "Bookmark Event" %>
      <% end %>
    <% end %>
  </div>

  <div id="event_show_info">
    <h2><%= @event.title %></h2></br>
    <ul>
      <li><%= Time.parse(@event.datetime_local).strftime("%I:%M %p") %></li></br>
      <li><%= Time.parse(@event.datetime_local).strftime("%A %B %d") %></li></br>
      <li><%= link_to @event.venue_name, venue_path(@event.api_venue_id), data: { no_turbolink: true } %></li></br>
      <li><%= @event.city_name.to_s + ", " + @event.state_prov.to_s %></li></br>
      <li><%= @event.country_name %></li></br></br>

      <%if @event.avg_price == "" || @event.avg_price.to_s.empty? %>
        <li><%= "Avg Ticket Price: Not available" %></li>
      <% else %>
        <li><%= "Avg Ticket Price:" %></li></br>
        <li><%= "$" + @event.avg_price.to_s %></li>
      <% end %>
    </ul>

    </br>
    </br>
    </br>
    </br>

    <!-- <ul> -->
      <!-- <li><h2>Performers:</h2></li></br> -->

      <%#if @performers %>
        <%# @performers.each do |performer| %>
          <!-- <li><%#= performer %></li></br> -->
        <%# end %>
      <%# end %>
    <!-- </ul> -->
  </div>

  <!-- <div id="event_show_recommendations_container">
    <h2>Other Recommended Events:</h2>
    <table class="event_show_recommended_events">
      <tr>
        <th>Event 1 sadfas dfasdfasd fasdfads fasd fas dfasdfad kjh lkjh lkjh lj lkjh klj lkj klhkjkjhl fadf</th>
        <th>Event 2 sdfsdfadfasdfadfafdsafda</th>
        <th>Event 3</th>
      </tr>
      <tr>
        <td><img src="http://placehold.it/200x200"></td>
        <td><img src="http://placehold.it/200x200"></td>
        <td><img src="http://placehold.it/200x200"></td>
      </tr>
    </table>
  </div> -->

</div>