config/routes.rb
Rails.application.routes.draw do
  
  root :to => 'events#home'
  resources :user_sessions
  resources :users
  resources :events
  resources :venues
  resources :bookmarks

  resources :events do
    resources :venues
    resources :bookmarks, only: [:create]
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/seatgeek/venue.rb
module Seatgeek

  class Venue < Base
    attr_reader :api_venue_id, :name, :timezone, :city, :state_prov, :postal_zip_code, :country, :tickets_url
    attr_accessor :address, :extended_address, :latitude, :longitude

    def initialize(attributes)
      @api_venue_id = attributes['id']
      @name = attributes["name"]
      @timezone = attributes["timezone"]
      @address = attributes["address"]
      @city = attributes["city"]
      @state_prov = attributes["state"]
      @postal_zip_code = attributes["postal_code"]
      @extended_address = attributes["address"] + ", " + attributes["city"] + ", " + attributes["state"] + ", " + attributes["postal_code"] + ", " + attributes["country"]
      @country = attributes["country"]
      @tickets_url = attributes['url']
      @latitude = attributes["location"]["lat"].to_f
      @longitude = attributes["location"]["lon"].to_f
    end

    def self.venue_search(keywords)
      response = get("/venues?q=#{keywords.to_s.gsub(' ','-')}&per_page=1000&page=1&client_id=#{ENV['seatgeek_id']}&client_secret=#{ENV['seatgeek_secret']}")

      response["venues"].map do |venue|
        new(venue)
      end
    end

    def self.venue_find(id)
      response = get("/venues?id=#{id}&client_id=#{ENV['seatgeek_id']}&client_secret=#{ENV['seatgeek_secret']}")
      new(response["venues"][0])
    end

    def self.to_h(venue)
      {
      api_venue_id: venue.api_venue_id,
      name: venue.name,
      timezone: venue.timezone,
      address: venue.address,
      extended_address: venue.extended_address,
      city: venue.city,
      state_prov: venue.state_prov,
      postal_zip_code: venue.postal_zip_code,
      country: venue.country,
      tickets_url: venue.tickets_url,
      latitude: venue.latitude,
      longitude: venue.longitude
      }
    end
  end

end

app/models/venue.rb
class Venue < ActiveRecord::Base
  geocoded_by :extended_address
  has_many :events
  
  def self.geocode(venue)
    venue_to_geocode = venue
    geocoded_venue = venue_to_geocode.geocode
    venue_to_geocode.update(latitude: geocoded_venue[0])
    venue_to_geocode.update(longitude: geocoded_venue[1])
    return venue
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  skip_before_action :require_login, only: [:show]

  def index
  end

  def show
    if Venue.exists?(api_venue_id: params[:id])
      @venue = Venue.find_by(api_venue_id: params[:id])
    else
      venue = Seatgeek::Venue.venue_find(params[:id])
      create
      venue_to_update_lat_long = Venue.find_by(api_venue_id: params[:id])
      @venue = Venue.geocode(venue_to_update_lat_long)
    end
  end

  def create
    venue = Seatgeek::Venue.to_h(Seatgeek::Venue.venue_find(params[:id]))
    Venue.create(
      api_venue_id: venue[:api_venue_id],
      name: venue[:name],
      timezone: venue[:timezone],
      address: venue[:address],
      extended_address: venue[:extended_address],
      city: venue[:city],
      state_prov: venue[:state_prov],
      postal_zip_code: venue[:postal_zip_code],
      country: venue[:country],
      tickets_url: venue[:tickets_url],
      latitude: venue[:latitude],
      longitude: venue[:longitude]
      )
  end

  private
    def search_params
      params.require(:venue).permit(:id)
    end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.erb
<%= form_for(@venue) do |f| %>
  <% if @venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% @venue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :api_venue_id %><br>
    <%= f.number_field :api_venue_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :timezone %><br>
    <%= f.text_field :timezone %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state_prov %><br>
    <%= f.text_field :state_prov %>
  </div>
  <div class="field">
    <%= f.label :postal_zip_code %><br>
    <%= f.text_field :postal_zip_code %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :tickets_url %><br>
    <%= f.text_field :tickets_url %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :extended_address %><br>
    <%= f.text_field :extended_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/venues/edit.html.erb
<h1>Editing Venue</h1>

<%= render 'form' %>

<%= link_to 'Show', @venue %> |
<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Venues</h1>

<table>
  <thead>
    <tr>
      <th>Api venue</th>
      <th>Name</th>
      <th>Timezone</th>
      <th>Address</th>
      <th>City</th>
      <th>State prov</th>
      <th>Postal zip code</th>
      <th>Country</th>
      <th>Tickets url</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Extended address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @venues.each do |venue| %>
      <tr>
        <td><%= venue.api_venue_id %></td>
        <td><%= venue.name %></td>
        <td><%= venue.timezone %></td>
        <td><%= venue.address %></td>
        <td><%= venue.city %></td>
        <td><%= venue.state_prov %></td>
        <td><%= venue.postal_zip_code %></td>
        <td><%= venue.country %></td>
        <td><%= venue.tickets_url %></td>
        <td><%= venue.latitude %></td>
        <td><%= venue.longitude %></td>
        <td><%= venue.extended_address %></td>
        <td><%= link_to 'Show', venue %></td>
        <td><%= link_to 'Edit', edit_venue_path(venue) %></td>
        <td><%= link_to 'Destroy', venue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Venue', new_venue_path %>

app/views/venues/new.html.erb
<h1>New Venue</h1>

<%= render 'form' %>

<%= link_to 'Back', venues_path %>

app/views/venues/show.html.erb
<div id="venue_show_container">

  <div id="map" data-latitude="<%= @venue.latitude %>" data-longitude="<%= @venue.longitude %>"> </div>

  <div id="venue_show_info">
    <h2><%= @venue.name %></h2></br>
    <ul id="venue_info">
      <li><%= @venue.address %></li>
      <li><%= @venue.city.to_s + ", " + @venue.state_prov.to_s %></li>
      <li><%= @venue.country %></li>
      <li><%= @venue.postal_zip_code %></li>
    </ul>
  </div>

</div>