config/routes.rb
Rails.application.routes.draw do
  
  root :to => 'events#home'
  resources :user_sessions
  resources :users
  resources :events
  resources :venues
  resources :bookmarks

  resources :events do
    resources :venues
    resources :bookmarks, only: [:create]
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Theknow</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Calligraffitti|Reenie+Beanie|Unica+One|Rancho|Berkshire+Swash' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV["google_maps_api_key"]}&callback=initMap", async: true, defer: true%>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div id="nav">
      <header class="centered-navigation" role="banner">
        <div class="centered-navigation-wrapper">

          <div class="the_know_logo">
            <h1>the know</h1>
            <h2>Your Premier Destination for Event Listings</h2>
          </div>

          <a href="javascript:void(0)" id="js-centered-navigation-mobile-menu" class="centered-navigation-mobile-menu">MENU</a>
          <nav role="navigation">
            <ul id="js-centered-navigation-menu" class="centered-navigation-menu show">

              <li class="nav-link">
                <a href="javascript:void(0)">
                  <!-- <% if current_user %>
                    Bookmarks
                  <% end %> -->
                </a>
              </li>

              <li class="nav-link">
                <a href="javascript:void(0)">
                  <p>About</p>
                </a>
              </li>

              <li class="nav-link">
                <a href="javascript:void(0)">
                    <%=link_to "Main", events_path %>
                </a>
              </li>

              <li class="nav-link">
                <a href="javascript:void(0)">
                  <% if current_user %>
                    <%= link_to "Logout", :logout, method: :post %>
                  <% else %>
                    <%= link_to "Login", :login %>
                  <% end %>
                </a>
              </li>

              <li class="nav-link">
                <a href="javascript:void(0)">
                  <%= link_to "Register", new_user_path %>
                </a>
              </li>

              <li class="nav-link">
                <a href="javascript:void(0)">
                  <% if current_user %>
                    <%=link_to "Profile", user_path(current_user.id),'data-no-turbolink' => true %>
                  <% end %>
                </a>
              </li>

            </ul>
          </nav>
        </div>
      </header>
    </div>

    <div>
      <p id="notice"><%= flash[:notice] %></p>
      <p id="alert"><%= flash[:alert] %></p>
    </div>

  <%= yield %>

  </body>
</html>

app/views/layouts/home_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Theknow</title>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'home' , media: 'all', 'data-turbolinks-track' => true %>
    <%= yield(:head)%>
  </head>

  <body>
    <div class="the-know-wrap">
      <div class="concert_pic">
        <%=image_tag("concert.jpg")%>
      </div>

      <div class="the_know_text">
        <h1>the know</h1>
        <h2>Your Premier Destination for Event Listings</h2>
      </div>
    </div>
    <div class="cirrcle">
      <p class="enter"><%= link_to "Enter", events_path %></p>
    </div>
  </div>
  </body>
</html>